
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("f2dad8a6-f107-4dc8-abef-0cf8b3960a8b")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("VehicleModel", "FK_Vehicle_Country", "Country", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(VehicleModel.Country), "Vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(VehicleModel.Vehicle), True)>

#End Region

Namespace VehicleModel

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class VehicleEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new VehicleEntities object using the connection string found in the 'VehicleEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=VehicleEntities", "VehicleEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new VehicleEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "VehicleEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new VehicleEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "VehicleEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Countries() As ObjectSet(Of Country)
            Get
                If (_Countries Is Nothing) Then
                    _Countries = MyBase.CreateObjectSet(Of Country)("Countries")
                End If
                Return _Countries
            End Get
        End Property
    
        Private _Countries As ObjectSet(Of Country)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Vehicles() As ObjectSet(Of Vehicle)
            Get
                If (_Vehicles Is Nothing) Then
                    _Vehicles = MyBase.CreateObjectSet(Of Vehicle)("Vehicles")
                End If
                Return _Vehicles
            End Get
        End Property
    
        Private _Vehicles As ObjectSet(Of Vehicle)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Countries EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToCountries(ByVal country As Country)
            MyBase.AddObject("Countries", country)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Vehicles EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToVehicles(ByVal vehicle As Vehicle)
            MyBase.AddObject("Vehicles", vehicle)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="VehicleModel", Name:="Country")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Country
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Country object.
        ''' </summary>
        ''' <param name="countryCodeID">Initial value of the CountryCodeID property.</param>
        ''' <param name="countryID">Initial value of the CountryID property.</param>
        ''' <param name="countryName">Initial value of the CountryName property.</param>
        Public Shared Function CreateCountry(countryCodeID As Global.System.String, countryID As Global.System.Int32, countryName As Global.System.String) As Country
            Dim country as Country = New Country
            country.CountryCodeID = countryCodeID
            country.CountryID = countryID
            country.CountryName = countryName
            Return country
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CountryCodeID() As Global.System.String
            Get
                Return _CountryCodeID
            End Get
            Set
                If (_CountryCodeID <> Value) Then
                    OnCountryCodeIDChanging(value)
                    ReportPropertyChanging("CountryCodeID")
                    _CountryCodeID = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("CountryCodeID")
                    OnCountryCodeIDChanged()
                End If
            End Set
        End Property
    
        Private _CountryCodeID As Global.System.String
        Private Partial Sub OnCountryCodeIDChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCountryCodeIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CountryID() As Global.System.Int32
            Get
                Return _CountryID
            End Get
            Set
                OnCountryIDChanging(value)
                ReportPropertyChanging("CountryID")
                _CountryID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CountryID")
                OnCountryIDChanged()
            End Set
        End Property
    
        Private _CountryID As Global.System.Int32
        Private Partial Sub OnCountryIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnCountryIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CountryName() As Global.System.String
            Get
                Return _CountryName
            End Get
            Set
                OnCountryNameChanging(value)
                ReportPropertyChanging("CountryName")
                _CountryName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CountryName")
                OnCountryNameChanged()
            End Set
        End Property
    
        Private _CountryName As Global.System.String
        Private Partial Sub OnCountryNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCountryNameChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("VehicleModel", "FK_Vehicle_Country", "Vehicle")>
         Public Property Vehicles() As EntityCollection(Of Vehicle)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Vehicle)("VehicleModel.FK_Vehicle_Country", "Vehicle")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Vehicle)("VehicleModel.FK_Vehicle_Country", "Vehicle", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="VehicleModel", Name:="Vehicle")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Vehicle
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Vehicle object.
        ''' </summary>
        ''' <param name="vehicleID">Initial value of the VehicleID property.</param>
        ''' <param name="countryCodeID">Initial value of the CountryCodeID property.</param>
        ''' <param name="designation">Initial value of the Designation property.</param>
        ''' <param name="vehicleType">Initial value of the VehicleType property.</param>
        ''' <param name="crewNum">Initial value of the CrewNum property.</param>
        Public Shared Function CreateVehicle(vehicleID As Global.System.Int32, countryCodeID As Global.System.String, designation As Global.System.String, vehicleType As Global.System.String, crewNum As Global.System.Int32) As Vehicle
            Dim vehicle as Vehicle = New Vehicle
            vehicle.VehicleID = vehicleID
            vehicle.CountryCodeID = countryCodeID
            vehicle.Designation = designation
            vehicle.VehicleType = vehicleType
            vehicle.CrewNum = crewNum
            Return vehicle
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property VehicleID() As Global.System.Int32
            Get
                Return _VehicleID
            End Get
            Set
                If (_VehicleID <> Value) Then
                    OnVehicleIDChanging(value)
                    ReportPropertyChanging("VehicleID")
                    _VehicleID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("VehicleID")
                    OnVehicleIDChanged()
                End If
            End Set
        End Property
    
        Private _VehicleID As Global.System.Int32
        Private Partial Sub OnVehicleIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnVehicleIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CountryCodeID() As Global.System.String
            Get
                Return _CountryCodeID
            End Get
            Set
                OnCountryCodeIDChanging(value)
                ReportPropertyChanging("CountryCodeID")
                _CountryCodeID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CountryCodeID")
                OnCountryCodeIDChanged()
            End Set
        End Property
    
        Private _CountryCodeID As Global.System.String
        Private Partial Sub OnCountryCodeIDChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCountryCodeIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Designation() As Global.System.String
            Get
                Return _Designation
            End Get
            Set
                OnDesignationChanging(value)
                ReportPropertyChanging("Designation")
                _Designation = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Designation")
                OnDesignationChanged()
            End Set
        End Property
    
        Private _Designation As Global.System.String
        Private Partial Sub OnDesignationChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnDesignationChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Variation() As Global.System.String
            Get
                Return _Variation
            End Get
            Set
                OnVariationChanging(value)
                ReportPropertyChanging("Variation")
                _Variation = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Variation")
                OnVariationChanged()
            End Set
        End Property
    
        Private _Variation As Global.System.String
        Private Partial Sub OnVariationChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnVariationChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property NickName() As Global.System.String
            Get
                Return _NickName
            End Get
            Set
                OnNickNameChanging(value)
                ReportPropertyChanging("NickName")
                _NickName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("NickName")
                OnNickNameChanged()
            End Set
        End Property
    
        Private _NickName As Global.System.String
        Private Partial Sub OnNickNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnNickNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property VehicleType() As Global.System.String
            Get
                Return _VehicleType
            End Get
            Set
                OnVehicleTypeChanging(value)
                ReportPropertyChanging("VehicleType")
                _VehicleType = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("VehicleType")
                OnVehicleTypeChanged()
            End Set
        End Property
    
        Private _VehicleType As Global.System.String
        Private Partial Sub OnVehicleTypeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnVehicleTypeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CrewNum() As Global.System.Int32
            Get
                Return _CrewNum
            End Get
            Set
                OnCrewNumChanging(value)
                ReportPropertyChanging("CrewNum")
                _CrewNum = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CrewNum")
                OnCrewNumChanged()
            End Set
        End Property
    
        Private _CrewNum As Global.System.Int32
        Private Partial Sub OnCrewNumChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnCrewNumChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Cannon1() As Global.System.String
            Get
                Return _Cannon1
            End Get
            Set
                OnCannon1Changing(value)
                ReportPropertyChanging("Cannon1")
                _Cannon1 = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Cannon1")
                OnCannon1Changed()
            End Set
        End Property
    
        Private _Cannon1 As Global.System.String
        Private Partial Sub OnCannon1Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCannon1Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Cannon2() As Global.System.String
            Get
                Return _Cannon2
            End Get
            Set
                OnCannon2Changing(value)
                ReportPropertyChanging("Cannon2")
                _Cannon2 = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Cannon2")
                OnCannon2Changed()
            End Set
        End Property
    
        Private _Cannon2 As Global.System.String
        Private Partial Sub OnCannon2Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCannon2Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property MG1() As Global.System.String
            Get
                Return _MG1
            End Get
            Set
                OnMG1Changing(value)
                ReportPropertyChanging("MG1")
                _MG1 = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("MG1")
                OnMG1Changed()
            End Set
        End Property
    
        Private _MG1 As Global.System.String
        Private Partial Sub OnMG1Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnMG1Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property MG2() As Global.System.String
            Get
                Return _MG2
            End Get
            Set
                OnMG2Changing(value)
                ReportPropertyChanging("MG2")
                _MG2 = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("MG2")
                OnMG2Changed()
            End Set
        End Property
    
        Private _MG2 As Global.System.String
        Private Partial Sub OnMG2Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnMG2Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property MG3() As Global.System.String
            Get
                Return _MG3
            End Get
            Set
                OnMG3Changing(value)
                ReportPropertyChanging("MG3")
                _MG3 = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("MG3")
                OnMG3Changed()
            End Set
        End Property
    
        Private _MG3 As Global.System.String
        Private Partial Sub OnMG3Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnMG3Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Bomb1() As Global.System.String
            Get
                Return _Bomb1
            End Get
            Set
                OnBomb1Changing(value)
                ReportPropertyChanging("Bomb1")
                _Bomb1 = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Bomb1")
                OnBomb1Changed()
            End Set
        End Property
    
        Private _Bomb1 As Global.System.String
        Private Partial Sub OnBomb1Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnBomb1Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Bomb2() As Global.System.String
            Get
                Return _Bomb2
            End Get
            Set
                OnBomb2Changing(value)
                ReportPropertyChanging("Bomb2")
                _Bomb2 = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Bomb2")
                OnBomb2Changed()
            End Set
        End Property
    
        Private _Bomb2 As Global.System.String
        Private Partial Sub OnBomb2Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnBomb2Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Missile() As Global.System.String
            Get
                Return _Missile
            End Get
            Set
                OnMissileChanging(value)
                ReportPropertyChanging("Missile")
                _Missile = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Missile")
                OnMissileChanged()
            End Set
        End Property
    
        Private _Missile As Global.System.String
        Private Partial Sub OnMissileChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnMissileChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Torpedo() As Global.System.String
            Get
                Return _Torpedo
            End Get
            Set
                OnTorpedoChanging(value)
                ReportPropertyChanging("Torpedo")
                _Torpedo = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Torpedo")
                OnTorpedoChanged()
            End Set
        End Property
    
        Private _Torpedo As Global.System.String
        Private Partial Sub OnTorpedoChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnTorpedoChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ServiceYearStart() As Nullable(Of Global.System.Int32)
            Get
                Return _ServiceYearStart
            End Get
            Set
                OnServiceYearStartChanging(value)
                ReportPropertyChanging("ServiceYearStart")
                _ServiceYearStart = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ServiceYearStart")
                OnServiceYearStartChanged()
            End Set
        End Property
    
        Private _ServiceYearStart As Nullable(Of Global.System.Int32)
        Private Partial Sub OnServiceYearStartChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnServiceYearStartChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ServiceYearEnd() As Nullable(Of Global.System.Int32)
            Get
                Return _ServiceYearEnd
            End Get
            Set
                OnServiceYearEndChanging(value)
                ReportPropertyChanging("ServiceYearEnd")
                _ServiceYearEnd = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ServiceYearEnd")
                OnServiceYearEndChanged()
            End Set
        End Property
    
        Private _ServiceYearEnd As Nullable(Of Global.System.Int32)
        Private Partial Sub OnServiceYearEndChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnServiceYearEndChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("VehicleModel", "FK_Vehicle_Country", "Country")>
        Public Property Country() As Country
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Country)("VehicleModel.FK_Vehicle_Country", "Country").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Country)("VehicleModel.FK_Vehicle_Country", "Country").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property CountryReference() As EntityReference(Of Country)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Country)("VehicleModel.FK_Vehicle_Country", "Country")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Country)("VehicleModel.FK_Vehicle_Country", "Country", value)
                End If
            End Set
        End Property

        #End Region

    End Class

    #End Region

    
End Namespace
